version: '3.8'

services:
  first-service:
    image: cardsapi
    ports:
      - "3000:3000"
    deploy:
      replicas: 3

  second-service:
    image: cardsapi
    ports:
      - "3001:3000"
    deploy:
      replicas: 2
